name: "Docker Image Builder"

on:
    - push

env:
    PERSONNAL_ACCESS_TOKEN: "${{ secrets.PERSONNAL_ACCESS_TOKEN }}"
    DOCKERHUB_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
    DOCKERHUB_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout"
                uses: actions/checkout@v4.1.4

            -   name: "Set up QEMU"
                uses: docker/setup-qemu-action@v3

            -   name: "Get banana profile"
                run: |
                    git clone https://${{ env.PERSONNAL_ACCESS_TOKEN }}@github.com/Epitech/banana-coding-style-checker
                    mv banana-coding-style-checker/vera .
                    rm -rf banana-coding-style-checker
                    ls

            -   name: "Set up Docker Buildx"
                uses: docker/setup-buildx-action@v3
                with:
                    driver-opts: |
                        image=moby/buildkit:v0.12.0
                    buildkitd-flags: --debug
                    platforms: linux/arm64

            -   name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: "${{ env.DOCKERHUB_USERNAME }}"
                    password: "${{ env.DOCKERHUB_TOKEN }}"

            -   name: Build and push
                uses: docker/build-push-action@v5
                with:
                    context: .
                    push: true
                    platforms: linux/arm64
                    tags: ximaz/epitech-coding-style-aarch64:latest
