name: "Docker Image Builder"

on:
    - push

env:
    PERSONNAL_ACCESS_TOKEN: "${{ secrets.PERSONNAL_ACCESS_TOKEN }}"
    DOCKERHUB_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
    DOCKERHUB_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout"
                uses: actions/checkout@v4.1.4
                with:
                    fetch-depth: 0

            -
                name: "Set up AArch64"
                uses: docker/setup-qemu-action@v3

            -   name: "Set up Docker Buildx"
                uses: docker/setup-buildx-action@v3
                with:
                    platforms: linux/arm64
            -   name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: "${{ env.DOCKERHUB_USERNAME }}"
                    password: "${{ env.DOCKERHUB_TOKEN }}"

            -   name: "Get banana profile"
                run: |
                    git clone https://${{ env.PERSONNAL_ACCESS_TOKEN }}@github.com/Epitech/banana-coding-style-checker
                    mv banana-coding-style-checker/vera .
                    rm -rf banana-coding-style-checker

            -   name: Build and push
                uses: docker/build-push-action@v5
                with:
                    push: true
                    tags: ximaz/epitech-coding-style-aarch64:latest
                    cache-from: |
                        type=local,src=.
